kind: pipeline
name: Mystic Clang

steps:
- name: Building Mystic Clang
  image: ubuntu:bionic
  environment: 
    GH_TOKEN:
      from_secret: GH_TOKEN
    GITLAB_TOKEN:
      from_secret: GITLAB_TOKEN
    GITLAB_USERNAME:
      from_secret: GITLAB_USERNAME
    TG_BOT_TOKEN:
      from_secret: TG_BOT_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID

  commands:
    - bash clone
    - cd build-clang
    - bash dobuild.sh
