kind: pipeline
name: Mystic GCC

steps:
- name: Building Mystic GCC
  image: okta10/docker:ubuntu
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - bash clone
    - cd build-gcc
    - bash dosetup
    - bash build_arm32
    - bash build_arm64
    - bash build_x86
