kind: pipeline
name: Mystic GCC

steps:
- name: Building Mystic GCC
  image: okta10/docker:ubuntu
  environment: 
    GH_TOKEN:
      from_secret: GH_TOKEN
    TG_BOT_TOKEN:
      from_secret: TG_BOT_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID

  commands:
    - bash clone
    - cd build-gcc
    - bash dosetup
    - bash build_arm32
    - bash build_arm64
    - bash build_x86
